import { ClerkProvider } from '@clerk/nextjs';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { Footer } from './components/Footer';
import { Menu } from './components/Menu';
import './global.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <div className="flex flex-col h-screen">
            <Menu />
            <div className="container mx-auto p-6">{children}</div>
            <Footer />
          </div>
          <ToastContainer />
        </body>
      </html>
    </ClerkProvider>
  );
}
